spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/userDB
    username: safety
    password: safety
    driver-class-name: org.postgresql.Driver
